apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ekart-blue-deployment
spec:
  selector:
    matchLabels:
      app: ekart
      version: blue
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ekart
        version: blue
    spec:
      containers:
        - name: ekart
          image: akscloud.azurecr.io/shopping-cart:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster





